\c postgres
DROP DATABASE IF EXISTS mastermind;
CREATE DATABASE mastermind;
\c mastermind;

DROP TABLE IF EXISTS scores CASCADE;
CREATE TABLE IF NOT EXISTS scores (
  id SERIAL PRIMARY KEY,
  username TEXT,
  score INTEGER,
  difficulty TEXT
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(40) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  salt VARCHAR(64) NOT NULL
);